;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.Scan.Successful",DevComment="")
+GameplayTagList=(Tag="Event.Scannable.Destroyed",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Player.Scan.Successful",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Player.Score.Add.Sound",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Player.Score.Lose",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Scannable.Destroyed.Sound",DevComment="")
+GameplayTagList=(Tag="Player.Ability.GainScore",DevComment="")
+GameplayTagList=(Tag="Player.Ability.Scan",DevComment="")
+GameplayTagList=(Tag="Player.Ability.Scan.Cooldown",DevComment="")
+GameplayTagList=(Tag="Player.Ability.Scan.Cooldown.Magnitude",DevComment="")
+GameplayTagList=(Tag="Player.Ability.Score.Lose",DevComment="")
+GameplayTagList=(Tag="Player.Effect.Score",DevComment="Change in Player\'s Score")
+GameplayTagList=(Tag="Player.Effect.Score.Lose",DevComment="")
+GameplayTagList=(Tag="Test.Ability.Fail.One",DevComment="")
+GameplayTagList=(Tag="Test.Ability.Fail.Two",DevComment="")
+GameplayTagList=(Tag="Test.Ability.Scan.One",DevComment="")
+GameplayTagList=(Tag="Test.Ability.Scan.Two",DevComment="")

